['enhancements.css','map.css','bbq.css','ehsan.css','mel.css','exact.css'].forEach(href=>{if(!document.querySelector(`link[href="${href}"]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}});

const applyImage=(selector,src,position='center')=>{document.querySelectorAll(selector).forEach(el=>{el.style.backgroundImage=`url('${src}')`;el.style.backgroundSize='cover';el.style.backgroundPosition=position;el.style.backgroundRepeat='no-repeat'})};
applyImage('.riding-map','949ea614-f9a5-40ed-b8c8-67d624c22e9e.png','center');
applyImage('.bbq-photo','cd34ea15-e9c9-4f80-8677-8fd34706819d.png','center');
applyImage('.mel-photo','7efb8577-2a38-4503-b669-475c6c98a6f7.png','center 25%');
applyImage('.ehsan-photo','4839a9df-4885-4670-98ea-22979ef70a81.png','center 22%');

const menu=document.querySelector('.menu');const nav=document.querySelector('nav');if(menu&&nav){menu.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const progressBar=document.querySelector('.progress');if(!reduced){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}})},{threshold:.1,rootMargin:'0px 0px -20px'});document.querySelectorAll('.reveal').forEach((el,i)=>{el.style.transitionDelay=Math.min((i%3)*50,100)+'ms';observer.observe(el)});window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-window.innerHeight;const pct=h?window.scrollY/h*100:0;if(progressBar)progressBar.style.width=pct+'%'},{passive:true})}else{document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));if(progressBar)progressBar.style.display='none'}